add mosquitto

diff --git a/soa-ecu/Dockerfile b/soa-ecu/Dockerfile
--- a/soa-ecu/Dockerfile
+++ b/soa-ecu/Dockerfile
@@ -3,9 +3,25 @@ FROM chao123/someip-base:latest
 ARG USERNAME=someip
 ARG PASSWORD=someip
 
+RUN groupadd $USERNAME
+RUN useradd -d /home/$USERNAME -ms /bin/bash -g someip -G sudo $USERNAME
+RUN echo "$USERNAME:$PASSWORD" | chpasswd
+
+
 RUN apt-get -y install \
     boxes \
     cowsay fortune
+
+RUN echo "\n  \
+export PS1='\[\e[32;7m\][\u@\h \w]\$ \[\e[m\]' \n\
+clear \n\
+echo ' SOME/IP Development Environment ' | boxes -d columns -ac -s 46x6 \n\
+echo '~~~ Have fun!' \n\
+/usr/games/fortune | /usr/games/cowsay -W 55 -e @@ -T ~~\n\
+echo -e \n\
+echo -e \n\
+cd ~ " \
+>> /home/$USERNAME/.bashrc
 
 
 RUN mkdir -p /home/someip/protocolbuf
@@ -32,21 +48,93 @@ RUN cd /home/someip/vsomeip-build && \
     cd ../..
 
 
-RUN echo "\n  \
-export PS1='\[\e[32;7m\][\u@\h \w]\$ \[\e[m\]' \n\
-clear \n\
-echo ' SOME/IP Development Environment ' | boxes -d columns -ac -s 46x6 \n\
-echo '~~~ Have fun!' \n\
-/usr/games/fortune | /usr/games/cowsay -W 55 -e @@ -T ~~\n\
-echo -e \n\
-echo -e \n\
-cd ~ " \
->> /home/$USERNAME/.bashrc
 
-RUN groupadd $USERNAME
-RUN useradd -d /home/$USERNAME -ms /bin/bash -g someip -G sudo $USERNAME
+ENV VERSION=1.6.15 \
+    DOWNLOAD_SHA256=5ff2271512f745bf1a451072cd3768a5daed71e90c5179fae12b049d6c02aa0f \
+    GPG_KEYS=A0D6EEA1DCAE49A635A3B2F0779B22DFB3E717B7 \
+    LWS_VERSION=4.2.1 \
+    LWS_SHA256=842da21f73ccba2be59e680de10a8cce7928313048750eb6ad73b6fa50763c51
 
-RUN echo "$USERNAME:$PASSWORD" | chpasswd
+RUN set -x && \
+    apk --no-cache add --virtual build-deps \
+        build-base \
+        cmake \
+        gnupg \
+        linux-headers \
+        openssl-dev \
+        util-linux-dev && \
+    wget https://github.com/warmcat/libwebsockets/archive/v${LWS_VERSION}.tar.gz -O /tmp/lws.tar.gz && \
+    echo "$LWS_SHA256  /tmp/lws.tar.gz" | sha256sum -c - && \
+    mkdir -p /build/lws && \
+    tar --strip=1 -xf /tmp/lws.tar.gz -C /build/lws && \
+    rm /tmp/lws.tar.gz && \
+    cd /build/lws && \
+    cmake . \
+        -DCMAKE_BUILD_TYPE=MinSizeRel \
+        -DCMAKE_INSTALL_PREFIX=/usr \
+        -DDISABLE_WERROR=ON \
+        -DLWS_IPV6=ON \
+        -DLWS_WITHOUT_BUILTIN_GETIFADDRS=ON \
+        -DLWS_WITHOUT_CLIENT=ON \
+        -DLWS_WITHOUT_EXTENSIONS=ON \
+        -DLWS_WITHOUT_TESTAPPS=ON \
+        -DLWS_WITH_EXTERNAL_POLL=ON \
+        -DLWS_WITH_HTTP2=OFF \
+        -DLWS_WITH_SHARED=OFF \
+        -DLWS_WITH_ZIP_FOPS=OFF \
+        -DLWS_WITH_ZLIB=OFF && \
+    make -j "$(nproc)" && \
+    rm -rf /root/.cmake && \
+    wget https://mosquitto.org/files/source/mosquitto-${VERSION}.tar.gz -O /tmp/mosq.tar.gz && \
+    echo "$DOWNLOAD_SHA256  /tmp/mosq.tar.gz" | sha256sum -c - && \
+    wget https://mosquitto.org/files/source/mosquitto-${VERSION}.tar.gz.asc -O /tmp/mosq.tar.gz.asc && \
+    export GNUPGHOME="$(mktemp -d)" && \
+    found=''; \
+    for server in \
+        hkps://keys.openpgp.org \
+        hkp://keyserver.ubuntu.com:80 \
+        pgp.mit.edu \
+    ; do \
+        echo "Fetching GPG key $GPG_KEYS from $server"; \
+        gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$GPG_KEYS" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch GPG key $GPG_KEYS" && exit 1; \
+    gpg --batch --verify /tmp/mosq.tar.gz.asc /tmp/mosq.tar.gz && \
+    gpgconf --kill all && \
+    rm -rf "$GNUPGHOME" /tmp/mosq.tar.gz.asc && \
+    mkdir -p /build/mosq && \
+    tar --strip=1 -xf /tmp/mosq.tar.gz -C /build/mosq && \
+    rm /tmp/mosq.tar.gz && \
+    make -C /build/mosq -j "$(nproc)" \
+        CFLAGS="-Wall -O2 -I/build/lws/include" \
+        LDFLAGS="-L/build/lws/lib" \
+        WITH_ADNS=no \
+        WITH_DOCS=no \
+        WITH_SHARED_LIBRARIES=yes \
+        WITH_SRV=no \
+        WITH_STRIP=yes \
+        WITH_WEBSOCKETS=yes \
+        prefix=/usr \
+        binary && \
+    addgroup -S -g 1883 mosquitto 2>/dev/null && \
+    adduser -S -u 1883 -D -H -h /var/empty -s /sbin/nologin -G mosquitto -g mosquitto mosquitto 2>/dev/null && \
+    mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log && \
+    install -d /usr/sbin/ && \
+    install -s -m755 /build/mosq/client/mosquitto_pub /usr/bin/mosquitto_pub && \
+    install -s -m755 /build/mosq/client/mosquitto_rr /usr/bin/mosquitto_rr && \
+    install -s -m755 /build/mosq/client/mosquitto_sub /usr/bin/mosquitto_sub && \
+    install -s -m644 /build/mosq/lib/libmosquitto.so.1 /usr/lib/libmosquitto.so.1 && \
+    install -s -m755 /build/mosq/src/mosquitto /usr/sbin/mosquitto && \
+    install -s -m755 /build/mosq/src/mosquitto_passwd /usr/bin/mosquitto_passwd && \
+    install -m644 /build/mosq/mosquitto.conf /mosquitto/config/mosquitto.conf && \
+    install -Dm644 /build/lws/LICENSE /usr/share/licenses/libwebsockets/LICENSE && \
+    install -Dm644 /build/mosq/epl-v10 /usr/share/licenses/mosquitto/epl-v10 && \
+    install -Dm644 /build/mosq/edl-v10 /usr/share/licenses/mosquitto/edl-v10 && \
+    chown -R mosquitto:mosquitto /mosquitto && \
+    apk --no-cache add \
+        ca-certificates && \
+    apk del build-deps && \
+    rm -rf /build
 
 RUN mkdir -p /var/run/sshd
 
